import type { Config } from 'tailwindcss';

// Design tokens transposés depuis le site vanilla (index.html > tailwind-config).
// Thème Material-3 « Maryse Club ». Toute évolution du DA se fait ici.
const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#584044',
        'on-secondary-fixed': '#311118',
        'surface-container-low': '#fff0f0',
        'on-tertiary-container': '#aa8c90',
        'on-error-container': '#93000a',
        'surface-container-highest': '#efdfde',
        tertiary: '#251216',
        'primary-fixed': '#ffd9dd',
        'on-secondary-fixed-variant': '#633b42',
        outline: '#847374',
        'tertiary-fixed': '#fddade',
        'secondary-fixed': '#ffd9de',
        'surface-container': '#fbeae9',
        surface: '#fff8f7',
        'primary-container': '#4a1e26',
        primary: '#300a12',
        secondary: '#7e5259',
        'surface-dim': '#e7d6d6',
        'outline-variant': '#d6c2c3',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#feedec',
        background: '#fff8f7',
        'on-primary-fixed': '#350e16',
        'error-container': '#ffdad6',
        'surface-bright': '#fff8f7',
        'surface-variant': '#efdfde',
        'surface-tint': '#854f57',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#6a3840',
        'secondary-fixed-dim': '#f0b8c0',
        'on-surface-variant': '#514345',
        'on-secondary-container': '#7b5056',
        'inverse-surface': '#382e2e',
        'on-tertiary-fixed': '#291619',
        'secondary-container': '#ffc6ce',
        'on-background': '#221a1a',
        'inverse-primary': '#fab4bd',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#221a1a',
        'on-primary-container': '#c1828b',
        'tertiary-container': '#3b262a',
        'surface-container-high': '#f5e4e4',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#e0bec2',
        'primary-fixed-dim': '#fab4bd',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '8px',
        gutter: '24px',
        'margin-desktop': '64px',
        'container-max': '1200px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'headline-lg': ['Playfair Display', 'serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'body-lg': ['Work Sans', 'sans-serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'label-md': ['Work Sans', 'sans-serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        logo: ['Great Vibes', 'cursive'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};

export default config;
