-- Table de référence des allergènes.
--
-- Calquée sur `ingredient_refs` : un libellé (name), une infobulle (tooltip)
-- et une URL, plus les colonnes de convention (status, created_at).
--
-- À exécuter dans l'éditeur SQL de Supabase (projet mc-snowy), puis
-- régénérer les types : `npm run gen:types`.

create table if not exists public.allergens (
  id         bigint generated by default as identity primary key,
  name       text not null,           -- Libellé affiché
  tooltip    text,                    -- Infobulle (texte d'aide au survol)
  url        text,                    -- Lien d'information
  status     text default 'published',
  created_at timestamptz default now()
);

-- Sécurité par Row Level Security, comme les autres référentiels.
alter table public.allergens enable row level security;

-- Lecture ouverte à tous (référentiel public, comme les ingrédients/unités).
drop policy if exists "allergens_select_all" on public.allergens;
create policy "allergens_select_all"
  on public.allergens for select
  using (true);

-- Écriture réservée aux administrateurs (profiles.role = 'admin').
drop policy if exists "allergens_admin_write" on public.allergens;
create policy "allergens_admin_write"
  on public.allergens for all
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );
